import turtle
turtle.bgcolor("black")
my_hw = turtle.Turtle()
my_hw.shape("turtle")
my_hw.speed(0)

#Blue triangle
my_hw.penup()
my_hw.goto(-300, -200)
my_hw.pendown()
my_hw.color("blue")
my_hw.begin_fill()
my_hw.forward(600)
my_hw.left(90)
my_hw.forward(400)
my_hw.left(90)
my_hw.forward(600)
my_hw.left(90)
my_hw.forward(400)
my_hw.left(90)
my_hw.end_fill()

#Red triangle
my_hw.penup()
my_hw.color("red")
my_hw.goto(-300, -100)
my_hw.pendown()
my_hw.begin_fill()
my_hw.forward(600)
my_hw.left(90)
my_hw.forward(200)
my_hw.left(90)
my_hw.forward(600)
my_hw.left(90)
my_hw.forward(200)
my_hw.left(90)
my_hw.end_fill()

#Temple
my_hw.penup()
my_hw.color("white")
my_hw.goto(-150, -75)
my_hw.pendown()
my_hw.begin_fill()
my_hw.forward(300)
my_hw.left(130)
my_hw.forward(50)
my_hw.right(40)
my_hw.forward(50)

my_hw.left(42)
my_hw.forward(50)
my_hw.left(96)
my_hw.forward(50)
my_hw.right(96)
my_hw.forward(75)
my_hw.left(96)
my_hw.forward(75)
my_hw.right(96)
my_hw.forward(50)
my_hw.left(96)
my_hw.forward(50)
my_hw.left(40)
my_hw.forward(50)
my_hw.right(40)
my_hw.forward(50)
my_hw.end_fill()


turtle.done()
